# Generated by Django 3.1.2 on 2020-10-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yavs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='born_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
