# Generated by Django 3.1.2 on 2020-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yavs', '0002_auto_20201031_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='born_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
